src/Relhub/WebBundle/Entity/CommandResult.php
<?php

namespace Relhub\WebBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * CommandResult
 */
class CommandResult
{

    const STATUS_PENDING = 'STATUS_PENDING';
    const STATUS_SUCCESSFUL = 'STATUS_SUCCESSFUL';    
    const STATUS_APPROVED = 'STATUS_APPROVED';    
    const STATUS_FAILED = 'STATUS_FAILED';

    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $action;

    /**
     * @var string
     */
    private $stage;

    /**
     * @var integer
     */
    private $releaseId;

    /**
     * @var string
     */
    private $output;

    /**
     * @var string
     */
    private $status = self::STATUS_PENDING;

    /**
     * @var integer
     */
    private $user;

    /**
     * @var \DateTime
     */
    private $created;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set action
     *
     * @param string $action
     * @return CommandResult
     */
    public function setAction($action)
    {
        $this->action = $action;

        return $this;
    }

    /**
     * Get action
     *
     * @return string 
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Set stage
     *
     * @param string $stage
     * @return CommandResult
     */
    public function setStage($stage)
    {
        $this->stage = $stage;

        return $this;
    }

    /**
     * Get stage
     *
     * @return string 
     */
    public function getStage()
    {
        return $this->stage;
    }

    /**
     * Set releaseId
     *
     * @param integer $releaseId
     * @return CommandResult
     */
    public function setReleaseId($releaseId)
    {
        $this->releaseId = $releaseId;

        return $this;
    }

    /**
     * Get releaseId
     *
     * @return integer 
     */
    public function getReleaseId()
    {
        return $this->releaseId;
    }

    /**
     * Set output
     *
     * @param string $output
     * @return CommandResult
     */
    public function setOutput($output)
    {
        $this->output = $output;

        return $this;
    }

    /**
     * Get output
     *
     * @return string 
     */
    public function getOutput()
    {
        return $this->output;
    }

    /**
     * Set status
     *
     * @param string $status
     * @return CommandResult
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    public function setSuccessful() {
      $this->status = self::STATUS_SUCCESSFUL;
    }

    public function setFailed() {
      $this->status = self::STATUS_FAILED;
    }

    public function isSuccessful() {
      return $this->status == self::STATUS_SUCCESSFUL || $this->status == self::STATUS_APPROVED;
    }

    public function setApproved() {
      $this->status = self::STATUS_APPROVED;
    }

    public function isApproved() {
      return $this->status == self::STATUS_APPROVED;
    }

    public function isPending() {
      return $this->status == self::STATUS_PENDING;
    }



    public function isManual() {
      return $this->isApproved();
    }

    /**
     * Get status
     *
     * @return string 
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set user
     *
     * @param integer $user
     * @return CommandResult
     */
    public function setUser($user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return integer 
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     * @return CommandResult
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime 
     */
    public function getCreated()
    {
        return $this->created;
    }
}

src/Relhub/WebBundle/Controller/MainController.php
<?php

namespace Relhub\WebBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

use Relhub\WebBundle\Entity\Project;
use Relhub\WebBundle\Entity\ReleaseVersion;
use Relhub\WebBundle\Entity\ReleaseBuild;
use Relhub\WebBundle\Entity\CommandResult;

use Relhub\WebBundle\Form\ProjectType;
use Relhub\WebBundle\Form\ReleaseVersionType;
use Relhub\WebBundle\Form\ReleaseBuildType;




class MainController extends Controller
{
    public function indexAction()
    {
        return $this->listReleasesAction();
//        return $this->render('RelhubWebBundle:Main:index.html.twig');
    }

    public function listProjectsAction()
    {
        $projects = $this->getDoctrine()->getManager()->getRepository('RelhubWebBundle:Project')->findAll();
        $data = array('projects' => $projects);
        return $this->render('RelhubWebBundle:Main:listProjects.html.twig', 
          array_merge($data, $this->getCommonData())
        );
    }

    public function createProjectAction(Request $request)
    {

      $project = new Project();
      $form = $this->createForm(new ProjectType(), $project);
      $form->handleRequest($request);
      if ($form->isValid() ) {
        $em = $this->getDoctrine()->getManager();
        $em->persist($project);
        $em->flush();

        $this->get('session')->getFlashBag()->set('success', 'Project Created');
        return $this->redirect($this->generateUrl('relhub_web_projects'));

      }

      $data = array('form' => $form->createView());
      return $this->render('RelhubWebBundle:Main:createProject.html.twig', 
        array_merge($data, $this->getCommonData())
      );
    }

    public function editProjectAction(Request $request, $project)
    {
      $em = $this->getDoctrine()->getManager();
      $project = $em->getRepository('RelhubWebBundle:Project')->find($project);


      $form = $this->createForm(new ProjectType(), $project);
      $form->handleRequest($request);
      if ($form->isValid() ) {
        $em = $this->getDoctrine()->getManager();
        $em->persist($project);
        $em->flush();

        $this->get('session')->getFlashBag()->set('success', 'Project Updated');
        return $this->redirect($this->generateUrl('relhub_web_projects'));

      }

      $data = array('form' => $form->createView(), 'project'=> $project);
      return $this->render('RelhubWebBundle:Main:editProject.html.twig', 
        array_merge($data, $this->getCommonData())
      );
    }



    public function listReleasesAction()
    {

/*      $releases = $this->getDoctrine()
            ->getRepository('RelhubWebBundle:ReleaseVersion')
            ->getReleasesForDisplay();*/

      $rep = $this->get('relhub_web.release_version');
      $releases = $rep->getReleasesForDisplay();
      $data = array(
          'releases' => $releases,
        );
      return $this->render('RelhubWebBundle:Main:listReleases.html.twig', 
        array_merge($data, $this->getCommonData())
      );

    }

    public function listProjectReleasesAction($project)
    {

      $em = $this->getDoctrine()->getManager();
      $project = $em->getRepository('RelhubWebBundle:Project')->findByName($project);
      $rep = $this->get('relhub_web.release_version');
      $releases = $rep->getReleasesForDisplay($project);
      $data = array(
          'releases' => $releases,
        );
      return $this->render('RelhubWebBundle:Main:listReleases.html.twig', 
        array_merge($data, $this->getCommonData())
      );

    }

    public function createReleaseAction(Request $request, $project)
    {    
      $release = new ReleaseVersion();
      $em = $this->getDoctrine()->getManager();
      $project = $em->getRepository('RelhubWebBundle:Project')->find($project);

      $release->setActions($project->getActions());
      $release->setOptions($project->getOptions());
      $form = $this->createForm(new ReleaseVersionType(), $release);
      $form->handleRequest($request);
      if ($form->isValid() ) {
        $em = $this->getDoctrine()->getManager();
        $release->setCreated(new \DateTime());
        $release->setStatus(ReleaseVersion::STATUS_PENDING);
        $em->persist($release);
        $em->flush();

        $this->get('session')->getFlashBag()->set('success', 'Release Created');
        return $this->redirect($this->generateUrl('relhub_web_projects'));
      }
      $data = array('form' => $form->createView());
      return $this->render('RelhubWebBundle:Main:createRelease.html.twig', 
        array_merge($data, $this->getCommonData())
      );
    }

    public function editReleaseAction(Request $request, $release)
    {    
      $em = $this->getDoctrine()->getManager();
      $release = $em->getRepository('RelhubWebBundle:ReleaseVersion')->find($release);


      //$release->setActions($project->getActions());
      $form = $this->createForm(new ReleaseVersionType(), $release);
      $form->handleRequest($request);
      if ($form->isValid() ) {
        $em = $this->getDoctrine()->getManager();
//        $release->setCreated(new \DateTime());
//        $release->setStatus(ReleaseVersion::STATUS_PENDING);
        $em->persist($release);
        $em->flush();

        $this->get('session')->getFlashBag()->set('success', 'Release Updated');
        return $this->redirect($this->generateUrl('relhub_web_releases'));
      }

      $data = array(
          'form' => $form->createView(),
          'release' => $release
        );

      return $this->render('RelhubWebBundle:Main:editRelease.html.twig', 
        array_merge($data, $this->getCommonData())
      );
    }



    public function buildReleaseStageAction(Request $request, $release, $stage)
    {    

      $em = $this->getDoctrine()->getManager();
      $release = $em->getRepository('RelhubWebBundle:ReleaseVersion')->find($release);

      $releaseVersion = $this->get('relhub_web.release_version');
      $currentVersion = $releaseVersion->getReleasesCurrentStage($release);
      if ($currentVersion != $stage) {
        throw $this->createNotFoundException('Release stage not valid');
      }

      $actions = $releaseVersion->getBuildableActionsForStage($release, $stage);
      
     

      $build = new ReleaseBuild();
      $build->setActions($actions);
      $build->setStage($stage);
      $form = $this->createForm(new ReleaseBuildType(), $build);
      $form->handleRequest($request);
      if ($form->isValid() ) {
        $user = $this->get('security.context')->getToken()->getUser();
        $build->setCreated(new \DateTime());
        $build->setStatus(ReleaseBuild::STATUS_PENDING);
        $build->setReleaseVersion($release);
        $build->setUser($user);
        $em->persist($build);

        foreach ($actions as $action) { 
          $commandResult = new CommandResult();
          $commandResult->setAction($action);
          $commandResult->setStage($stage);
          $commandResult->setReleaseId($release->getId());
          $commandResult->setUser($user);
          $commandResult->setCreated(new \DateTime());
          $em->persist($commandResult);
        }
        $em->flush();
        $this->get('session')->getFlashBag()->set('success', 'Release Build Created');
        return $this->redirect($this->generateUrl('relhub_web_releases'));
      }

      $data = array(
          'form' => $form->createView(),
          'release' => $release,
          'actions' => $actions
        );

      return $this->render('RelhubWebBundle:Main:buildRelease.html.twig', 
        array_merge($data, $this->getCommonData())
      );

    }

    public function approveReleaseStageAction(Request $request, $release, $stage)
    {    
      $em = $this->getDoctrine()->getManager();
      $release = $em->getRepository('RelhubWebBundle:ReleaseVersion')->find($release);

      $approveActions = $request->get('action');
      $releaseVersion = $this->get('relhub_web.release_version');

      $currentVersion = $releaseVersion->getReleasesCurrentStage($release);
      if ($currentVersion != $stage) {
        throw $this->createNotFoundException('Release stage not valid');
      }

      if (empty($approveActions)) {
        throw $this->createNotFoundException('Actions to approve must be given');
      }

      $build = new ReleaseBuild();      
      $form = $this->createForm(new ReleaseBuildType(), $build);
      $form->handleRequest($request);
      var_dump('form valid:: ');
      var_dump($form->isValid());
      if ($form->isValid() ) {

        $user = $this->get('security.context')->getToken()->getUser();
        var_dump($user);
        /*$build->setCreated(new \DateTime());
        $build->setStatus(ReleaseBuild::STATUS_PENDING);
        $build->setReleaseVersion($release);
        $build->setUser($user);
        $em->persist($build);
        $em->flush();*/

        $em = $this->getDoctrine()->getManager();
        foreach ($approveActions as $action) {
          $command = new CommandResult(); 
          $command->setAction($action);
          $command->setStage($stage);
          $command->setReleaseId($release->getId());
          $command->setUser($user);
          $command->setApproved();
          $command->setCreated(new \DateTime());

          $em->persist($command);
        }

        $em->flush();
        $this->get('session')->getFlashBag()->set('success', 'Release Actions Approved');
        return $this->redirect($this->generateUrl('relhub_web_releases'));
      }

      $data = array(
          'stage' => $stage,
          'form' => $form->createView(),
          'release' => $release,
          'actions' => $approveActions
        );

      return $this->render('RelhubWebBundle:Main:approveReleaseStage.html.twig', 
        array_merge($data, $this->getCommonData())
      );

    }



    public function publishReleaseAction(Request $request, $release)
    {    

      $em = $this->getDoctrine()->getManager();

src/Relhub/WebBundle/Resources/views/Main/approveReleaseStage.html.twig
{% extends '::base.html.twig' %}

{% block title %}ReleaseHub: Approve {{ release }} {{stage}} stage{% endblock %}

{% block body %}
<h1>Approve {{ release }} {{stage}} stage</h1>

{{ form_start(form) }}

<ul>
  {% for action in actions %}
    <li>{{action}}
  <input type="hidden" name="action[]" value="{{action}}"/>
</li>
  {% endfor %}
</ul>
{{ form(form) }}

{{ form_end(form) }}

{% endblock %}

src/Relhub/WebBundle/Resources/views/Main/buildRelease.html.twig
{% extends '::base.html.twig' %}

{% block title %}ReleaseHub: Build {{ release }}{% endblock %}

{% block body %}
<h1>Build {{ release }}</h1>

{{ form(form) }}

{% endblock %}

src/Relhub/WebBundle/Resources/views/Main/createProject.html.twig
{% extends '::base.html.twig' %}

{% block title %}ReleaseHub: Create Project{% endblock %}

{% block body %}

{{ form(form) }}

{% endblock %}

src/Relhub/WebBundle/Resources/views/Main/createRelease.html.twig
{% extends '::base.html.twig' %}

{% block title %}ReleaseHub: Create Release{% endblock %}

{% block body %}
<h1>Create Release</h1>

{{ form(form) }}

{% endblock %}

src/Relhub/WebBundle/Resources/views/Main/editProject.html.twig
{% extends '::base.html.twig' %}

{% block title %}ReleaseHub: Edit Project {{ project }}{% endblock %}

{% block body %}
<h1>Edit Project {{ project }}</h1>
{{ form(form) }}

{% endblock %}

src/Relhub/WebBundle/Resources/views/Main/editRelease.html.twig
{% extends '::base.html.twig' %}

{% block title %}ReleaseHub: Edit Release: {{release}}{% endblock %}

{% block body %}
<h1>Edit Release</h1>

{{ form(form) }}

{% endblock %}

src/Relhub/WebBundle/Resources/views/Main/index.html.twig
{% extends '::base.html.twig' %}

{% block title %}ReleaseHub{% endblock %}

{% block body %}
Release hub body
{% endblock %}

src/Relhub/WebBundle/Resources/views/Main/listProjects.html.twig
{% extends '::base.html.twig' %}

{% block title %}ReleaseHub{% endblock %}

{% block body %}



<h1 id="container">Projects</h1>
{% for project in projects %}
<div class="panel panel-default">
  <div class="panel-body">
    <h3>{{project.name }}</h3>
    <a href="{{ path('relhub_web_project_edit', {'project': project.id}) }}">Edit Project</a>
  </div>
</div>
{% endfor %}

{% endblock %}

src/Relhub/WebBundle/Resources/views/Main/listReleases.html.twig
{% extends '::base.html.twig' %}

{% block title %}ReleaseHub{% endblock %}
{% block body %}

<script type="text/javascript">

function toggleCommandDetails(id) {
console.log('toggle command :: '+id);
  $('#' + id).toggle();

}
</script>



<div class="bs-component">
<div class="navbar-collapse collapse navbar-inverse-collapse">
  <ul class="nav navbar-nav">
    <li class="active">
      <a href="{{ path('relhub_web_release_create') }}">Create Release</a>
    </li>
  </ul>
</div>
</div>


<h1 id="container">Releases</h1>
{% for release_details in releases %}

<div class="page-header">
  <h3>{{release_details.release.name }}</h3>
            </div>

  <a href="{{ path('relhub_web_release_edit', {'release': release_details.release.id}) }}">Edit Release</a>
  <form 
    method="POST"
    {% if release_details.hasApprovable %}
  action="{{ path('relhub_web_release_approve_stage', {'release': release_details.release.id, 'stage': release_details.currentStage}) }}"
    {% elseif release_details.hasBuildable %}
  action="{{ path('relhub_web_release_build', {'release': release_details.release.id, 'stage': release_details.currentStage}) }}"
    {% endif %}

  >

    {% for stage in release_details.stages %}
    <div class="panel 
{% if stage in release_details.failedStages %}
panel-danger
{% elseif stage in release_details.successfulStages %}
panel-success
{% elseif stage == release_details.currentStage %}
panel-primary
{% else %}
panel-default
{% endif %}
">
      <div class="panel-heading">{{ stage }}</div>
      <div class="panel-body">
        {% for action in release_details.actions[stage] %} 
        <div class="list-group-item">
          {{ action.action }}
          {% if action.isApprovable %}
            <input type="checkbox" name="action[]"  value="{{ action.action }} "/>
            <label>Approve</label>
          {% endif %}
        
          {% if action.command.status %}                
            <div style="float:right;">
              {% if action.command.successful %}        
                {% if action.command.manual %}
                  <button type="button" class="btn btn-primary btn-xs" onclick="toggleCommandDetails('command-details-{{action.command.id}}');">Approved</button>
                {% else %}
                  <button type="button" class="btn btn-primary btn-xs" onclick="toggleCommandDetails('command-details-{{action.command.id}}');">Success</button>
                {% endif %}
              {% elseif action.command.pending %}        
                  <button type="button" class="btn btn-info btn-xs">Pending</button>
              {% else %}
                <button type="button" class="btn btn-danger btn-xs" onclick="toggleCommandDetails('command-details-{{action.command.id}}');">Failed</button>
              {% endif %}
            </div>

            {% if not action.command.pending %}        
            <div class="command-details" id="command-details-{{action.command.id}}">
              <div class="user">
                {% if action.command.manual %}
                Approved
                {% else %}
                Run
                {% endif %}
                by <strong>{{ action.command.user }}</strong> on <strong>{{ action.command.created|date("F jS \\a\\t g:ia") }}</strong>
              </div>        
              {% if not action.command.manual %}
              <div class="output">
                {{ action.command.output|trim }}
              </div>
              {% endif %}
              <div>
                <a class="btn btn-danger btn-xs"  href="{{ path('relhub_web_command_remove', {'command': action.command.id}) }}">Delete command result</a> 
              </div>
            </div>            
            {% endif %}
          {% endif %}
         
        </div>
        {% endfor %}
      </div>
    </div>
    {% endfor %}

    <div>

      {% if release_details.hasApprovable %}
        <button type="submit" class="btn btn-primary">Approve {{ release_details.currentStage}} stage</button>
      {% elseif release_details.hasBuildable %}
        <a href="{{ path('relhub_web_release_build', {'release': release_details.release.id, 'stage': release_details.currentStage}) }}"><button type="submit" class="btn btn-primary">Run {{ release_details.currentStage}} stage</button></a>
      {% endif %}

    </div>

  </form>
{% endfor %}



{% endblock %}

src/Relhub/WebBundle/Resources/views/Main/publishRelease.html.twig
{% extends '::base.html.twig' %}

{% block title %}ReleaseHub: Publish {{ release }}{% endblock %}

{% block body %}
<h1 id="container">Publish {{ release }}</h1>

{{ form(form) }}

{% endblock %}